swagger: "2.0"
info:
  version: "0.1"
  title: Wazo Plugind
  description: "Wazo's plugin management service"
  contact:
    name: Wazo dev team
    url: http://wazo.community
    email: dev@wazo.community
  license:
    name: GPLv3
    url: http://www.gnu.org/licenses/gpl-3.0.html
x-xivo-port: 9503
x-xivo-name: plugind
basePath: /0.1
schemes:
- https
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  xivo_auth_token:
    type: apiKey
    name: X-Auth-Token
    in: header
security:
  - xivo_auth_token: []
paths:
  /config:
    get:
      produces:
        - application/json
      summary: Show the current configuration
      description: '**Required ACL:** `plugind.config.read`'
      operationId: getConfig
      tags:
        - config
      responses:
        '200':
          'description': The configuration of the service
  /plugins:
    post:
      tags:
        - plugin
      summary: Install a plugin
      description: |
        **Required ACL:** `plugind.plugins.create`

        Allow the administrator to install a plugin on the server.
        ---

        To install a plugin that is not registered on the market:

        ```json
        {"url": "<URL to the plugin>", "method": "git"}
        ```
      parameters:
        - name: body
          in: body
          description: "The plugins' installation parameters"
          schema:
            $ref: '#/definitions/PluginInstallParameters'
      responses:
        '200':
          description: "Installation started"
          schema:
            $ref: '#/definitions/InstallResponse'
definitions:
  InstallResponse:
    type: object
    properties:
      uuid:
        type: string
        description: "A UUID associated to this plugin installation"
  PluginInstallParameters:
    type: object
    properties:
      url:
        type: string
        description: "The URL to fetch the plugin"
      method:
        type: string
        description: "The method used to fetch this plugin"
        enum: [git]
    required:
      - url
      - method
